services:
  db:
    image: postgres
    container_name: postgres_glasskube
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: glasskube
    volumes:
      - /Users/chris/dev/private/sql-storage:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: spring-boot_glasskube
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/glasskube
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - db
    restart: always
